# CMake generated Testfile for 
# Source directory: /home/jesse/sandbox/llama.cpp/tests
# Build directory: /home/jesse/sandbox/llama.cpp/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-tokenizer-0-bert-bge "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-0" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-bert-bge.gguf")
set_tests_properties(test-tokenizer-0-bert-bge PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;114;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-command-r "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-0" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-command-r.gguf")
set_tests_properties(test-tokenizer-0-command-r PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;115;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-deepseek-coder "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-0" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-deepseek-coder.gguf")
set_tests_properties(test-tokenizer-0-deepseek-coder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;116;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-deepseek-llm "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-0" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-deepseek-llm.gguf")
set_tests_properties(test-tokenizer-0-deepseek-llm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;117;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-falcon "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-0" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-falcon.gguf")
set_tests_properties(test-tokenizer-0-falcon PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;118;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-gpt-2 "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-0" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-gpt-2.gguf")
set_tests_properties(test-tokenizer-0-gpt-2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;119;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-llama-bpe "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-0" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-llama-bpe.gguf")
set_tests_properties(test-tokenizer-0-llama-bpe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;120;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-llama-spm "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-0" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-llama-spm.gguf")
set_tests_properties(test-tokenizer-0-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;121;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-mpt "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-0" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-mpt.gguf")
set_tests_properties(test-tokenizer-0-mpt PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;122;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-phi-3 "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-0" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-phi-3.gguf")
set_tests_properties(test-tokenizer-0-phi-3 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;123;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-qwen2 "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-0" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-qwen2.gguf")
set_tests_properties(test-tokenizer-0-qwen2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;124;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-refact "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-0" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-refact.gguf")
set_tests_properties(test-tokenizer-0-refact PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;125;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-starcoder "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-0" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-starcoder.gguf")
set_tests_properties(test-tokenizer-0-starcoder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;126;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizers-ggml-vocabs "/home/jesse/sandbox/llama.cpp/tests/test-tokenizers-repo.sh" "https://huggingface.co/ggml-org/vocabs" "/home/jesse/sandbox/llama.cpp/models/ggml-vocabs")
set_tests_properties(test-tokenizers-ggml-vocabs PROPERTIES  LABELS "main" WORKING_DIRECTORY "/home/jesse/sandbox/llama.cpp/bin" _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;64;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;129;llama_test_cmd;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-sampling "/home/jesse/sandbox/llama.cpp/bin/test-sampling")
set_tests_properties(test-sampling PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;143;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-grammar-parser "/home/jesse/sandbox/llama.cpp/bin/test-grammar-parser")
set_tests_properties(test-grammar-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;144;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-grammar-integration "/home/jesse/sandbox/llama.cpp/bin/test-grammar-integration")
set_tests_properties(test-grammar-integration PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;145;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-llama-grammar "/home/jesse/sandbox/llama.cpp/bin/test-llama-grammar")
set_tests_properties(test-llama-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;146;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-chat "/home/jesse/sandbox/llama.cpp/bin/test-chat")
set_tests_properties(test-chat PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;147;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-json-schema-to-grammar "/home/jesse/sandbox/llama.cpp/bin/test-json-schema-to-grammar")
set_tests_properties(test-json-schema-to-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "/home/jesse/sandbox/llama.cpp" _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;150;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-1-llama-spm "/home/jesse/sandbox/llama.cpp/bin/test-tokenizer-1-spm" "/home/jesse/sandbox/llama.cpp/models/ggml-vocab-llama-spm.gguf")
set_tests_properties(test-tokenizer-1-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;176;llama_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-chat-parser "/home/jesse/sandbox/llama.cpp/bin/test-chat-parser")
set_tests_properties(test-chat-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;182;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-chat-template "/home/jesse/sandbox/llama.cpp/bin/test-chat-template")
set_tests_properties(test-chat-template PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;183;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-json-partial "/home/jesse/sandbox/llama.cpp/bin/test-json-partial")
set_tests_properties(test-json-partial PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;184;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-log "/home/jesse/sandbox/llama.cpp/bin/test-log")
set_tests_properties(test-log PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;185;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-regex-partial "/home/jesse/sandbox/llama.cpp/bin/test-regex-partial")
set_tests_properties(test-regex-partial PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;186;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-thread-safety "/home/jesse/sandbox/llama.cpp/bin/test-thread-safety" "-hf" "ggml-org/models" "-hff" "tinyllamas/stories15M-q4_0.gguf" "-ngl" "99" "-p" "The meaning of life is" "-n" "128" "-c" "256" "-ub" "32" "-np" "4" "-t" "2")
set_tests_properties(test-thread-safety PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;189;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-arg-parser "/home/jesse/sandbox/llama.cpp/bin/test-arg-parser")
set_tests_properties(test-arg-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;196;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-opt "/home/jesse/sandbox/llama.cpp/bin/test-opt")
set_tests_properties(test-opt PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;201;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-gguf "/home/jesse/sandbox/llama.cpp/bin/test-gguf")
set_tests_properties(test-gguf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;203;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-backend-ops "/home/jesse/sandbox/llama.cpp/bin/test-backend-ops")
set_tests_properties(test-backend-ops PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;204;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-model-load-cancel "/home/jesse/sandbox/llama.cpp/bin/test-model-load-cancel")
set_tests_properties(test-model-load-cancel PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;206;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-autorelease "/home/jesse/sandbox/llama.cpp/bin/test-autorelease")
set_tests_properties(test-autorelease PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;207;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-barrier "/home/jesse/sandbox/llama.cpp/bin/test-barrier")
set_tests_properties(test-barrier PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;211;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-quantize-fns "/home/jesse/sandbox/llama.cpp/bin/test-quantize-fns")
set_tests_properties(test-quantize-fns PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;212;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-quantize-perf "/home/jesse/sandbox/llama.cpp/bin/test-quantize-perf")
set_tests_properties(test-quantize-perf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;213;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-rope "/home/jesse/sandbox/llama.cpp/bin/test-rope")
set_tests_properties(test-rope PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;214;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-mtmd-c-api "/home/jesse/sandbox/llama.cpp/bin/test-mtmd-c-api")
set_tests_properties(test-mtmd-c-api PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;219;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-alloc "/home/jesse/sandbox/llama.cpp/bin/test-alloc")
set_tests_properties(test-alloc PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;227;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-sparse-attn "/home/jesse/sandbox/llama.cpp/bin/test-sparse-attn")
set_tests_properties(test-sparse-attn PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;231;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-sparse-attn-noalloc "/home/jesse/sandbox/llama.cpp/bin/test-sparse-attn-noalloc")
set_tests_properties(test-sparse-attn-noalloc PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;235;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-sparse-topk-radix "/home/jesse/sandbox/llama.cpp/bin/test-sparse-topk-radix")
set_tests_properties(test-sparse-topk-radix PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;238;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-sparse-mla-decode-cuda "/home/jesse/sandbox/llama.cpp/bin/test-sparse-mla-decode-cuda")
set_tests_properties(test-sparse-mla-decode-cuda PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;102;add_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;255;llama_build_and_test;/home/jesse/sandbox/llama.cpp/tests/CMakeLists.txt;0;")
